name: Golang Tests
on:
  pull_request:
    branches: [ '**' ]
  push:
    branches:
      - master
      - dev
      - devel
      - develop

  workflow_dispatch:
    branches: [ '**' ]

jobs:
  tests:
    strategy:
      matrix:
        go-version: [ 1.16.x ]
    runs-on: ubuntu-18.04
    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: run tests
        run: go test ./src/